[env:esp32-s3-super-mini]
platform = espressif32
board = lolin_s3_mini                    ##Using this as it aligns with the 4mb superminis i used with
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 80000000L            # CPU downclocked to minimize heating
board_build.filesystem = littlefs

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    majicdesigns/MD_Parola @ ^3.7.3
    majicdesigns/MD_MAX72XX @ ^3.5.1
    mathieucarbou/ESPAsyncWebServer @ ^3.1.1
    mathieucarbou/AsyncTCP @ ^3.2.4
